name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v6.0.2

    - name: Setup Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version: 3.11

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r -ll -ii . -f json --output bandit-scan-report.json

    - name: Upload artifact
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: Bandit scan report
        path: bandit-scan-report.json

  image_scan:
      name: Build image and run image scan
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v6.0.2

        - name: Setup docker
          uses: docker-practice/actions-setup-docker@v1
          with:
            docker-version: 29.5.2
            
        - name: Build docker image
          runs: docker build -t myapp . 

        - name: Docker Scout image scan
          uses: docker/scout-action@v1.21.0
          with:
            command: quickview, cves, recommendations
            
            
